[tool.poetry]
name = "pywelkin"
version = "0.1.0"
description = "Python implementaiton of Welkin, a personal information manager."
authors = [
    "Oscar Bender-Stone <oscarbenderstone@gmail.com>",
]
maintainers = [
    "Oscar Bender-Stone <oscarbenderstone@gmail.com>",
]
license = "LGPL-3.0-or-later"
readme = "README.org"
repository = "https://github.com/astral-bear/pywelkin"
keywords = ["graph", "organizer"]
packages = [
    {include = "core"},
    {include = "cli"},
    {include = "gui"},
    {include = "desktop"},
    {include = "ios"},
    {include = "android"},
]

[tool.poetry.dependencies]
python = ">=3.9, <3.12"
sphinx = {version = "^7.2.6"}
furo = "^2023.9.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
docs = ["sphinx", "furo"]
